In [12]:
import numpy as np

In [13]:
mylist=[1,2,3]
mylist

[1, 2, 3]

In [14]:
my=np.array(mylist)

In [15]:
my

array([1, 2, 3])

In [16]:
arr=[
    [1,2,3],
    [4,5,6],
    [7,8,9],
]

In [17]:
np.array(arr)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [19]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [20]:
np.zeros((5,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.zeros(3)

array([0., 0., 0.])

In [22]:
np.linspace(1,5,6)

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [23]:
np.linspace(0,50,10)

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [24]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [25]:
np.random.rand(3)

array([0.48664694, 0.01931158, 0.64409431])

In [26]:
np.random.rand(5,5)

array([[0.72574341, 0.03952928, 0.06889759, 0.27652884, 0.12337229],
       [0.21628732, 0.93581168, 0.39995646, 0.36324263, 0.58480329],
       [0.90296685, 0.00707448, 0.2132095 , 0.8510769 , 0.12719832],
       [0.40560133, 0.61429046, 0.672437  , 0.56292183, 0.3577053 ],
       [0.50486763, 0.13497185, 0.40370019, 0.89410712, 0.80449948]])

In [27]:
np.random.randn(2)

array([-0.38904676,  0.50428909])

In [28]:
np.random.randint(3,100,10)

array([45, 21, 65,  3, 66, 36, 28, 24, 22, 47])

In [29]:
arr=np.arange(25)
ranarr=np.random.randint(0,50,10)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
ranarr


array([25,  8, 47, 45, 12, 47, 49, 34,  1, 31])

In [32]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
ranarr.reshape(2,5)

array([[25,  8, 47, 45, 12],
       [47, 49, 34,  1, 31]])

In [34]:
ranarr.max()

49

In [35]:
arr.max()

24

In [36]:
arr.min()

0

In [40]:
arr.argmax()

24

In [38]:
ranarr.argmax()

6

In [39]:
arr.dtype


dtype('int32')