selection and broadcasting


In [46]:
import numpy as np


In [47]:
arr=np.arange(11)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr[5]

5

In [50]:
arr[1:10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
s=arr[0:5].copy()
s

array([0, 1, 2, 3, 4])

In [53]:
s[:]=100

In [54]:
s

array([100, 100, 100, 100, 100])

In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
arr2=np.array(([1,2,3],[3,6,7],[4,6,7]))

In [57]:
arr2

array([[1, 2, 3],
       [3, 6, 7],
       [4, 6, 7]])

In [78]:
arr2*arr2

array([[ 1,  4,  9],
       [ 9, 36, 49],
       [16, 36, 49]])

In [58]:
arr2[0]

array([1, 2, 3])

In [59]:
arr2[2,2]

7

In [75]:
arr2[1:,:2]

array([[3, 6],
       [4, 6]])

In [77]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [63]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [64]:
import numpy as np

In [65]:
arr1=np.arange(11)

In [66]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
arr1+arr1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

universal array functions


In [68]:
np.sqrt(arr1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [69]:
np.exp(arr1)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [70]:
np.max(arr1)

10

In [71]:
np.sin(arr1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [72]:
np.log(arr1)

C:\Users\abishek\AppData\Local\Temp\ipykernel_24968\2108464003.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr1)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])